name: wink
description: A new Flutter project.
publish_to: none
version: 1.0.0+3

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  firebase_core: ^2.7.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  rxdart: ^0.27.7
  test: ^1.21.1
  bloc_test: ^9.1.1
  equatable: ^2.0.3
  formz: ^0.4.0
  intl: ^0.18.0
  shared_preferences: ^2.0.20
  firebase_auth: ^4.2.2
  firebase_core_platform_interface: ^4.5.3
  google_sign_in: ^6.0.2
  meta: ^1.8.0
  get: ^4.6.5
  firebase_database: ^10.0.16
  nb_utils: ^5.0.6
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.4.0
  quiver: ^3.2.1
  google_fonts: ^4.0.3
  google_mobile_ads: ^3.0.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.5
  firebase_dynamic_links: ^5.2.0
  uni_links: ^0.5.1
  share_plus: ^4.5.3
  flutter_material_symbols: ^0.0.4
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.2.0
  image_picker: ^0.8.7+5
  in_app_purchase: ^3.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
