// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQZnMqTmeT5UyExnbeEMszwC-qxhooRI',
    appId: '1:887191585385:web:7085d0480156040227d8f8',
    messagingSenderId: '887191585385',
    projectId: 'wink-32bef',
    authDomain: 'wink-32bef.firebaseapp.com',
    storageBucket: 'wink-32bef.appspot.com',
    measurementId: 'G-T3W3E80XBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1pjI0D7wMX1NM21pFXePEt3nNVSBt6D4',
    appId: '1:887191585385:android:adae5178b1a0662c27d8f8',
    messagingSenderId: '887191585385',
    projectId: 'wink-32bef',
    storageBucket: 'wink-32bef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZsZNnwKHGmBeyn38KLzG7gdtMFOcITg',
    appId: '1:887191585385:ios:f4fe355afe09166827d8f8',
    messagingSenderId: '887191585385',
    projectId: 'wink-32bef',
    storageBucket: 'wink-32bef.appspot.com',
    iosClientId: '887191585385-3fh8icng8vo68nqcoejcpgm4ihualjfs.apps.googleusercontent.com',
    iosBundleId: 'com.springs.namp.wink.wink',
  );
}
